"""обавление поля test_task

Revision ID: 85acee4d5f51
Revises: f0dca337f90b
Create Date: 2024-11-03 21:46:41.840345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85acee4d5f51'
down_revision: Union[str, None] = 'f0dca337f90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_portrait')
    op.drop_table('vacancies')
    op.drop_table('candidates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name='candidates_vacancy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidates_pkey')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vacancies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conditions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responsibilities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interview_questions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('candidate_portrait',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ideal_candidate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('demographics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qualities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name='candidate_portrait_vacancy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidate_portrait_pkey'),
    sa.UniqueConstraint('vacancy_id', name='candidate_portrait_vacancy_id_key')
    )
    # ### end Alembic commands ###
