"""обавление полей Candidates

Revision ID: 9ae0e1d7c951
Revises: 23dfe50b231a
Create Date: 2024-11-06 22:05:15.205355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae0e1d7c951'
down_revision: Union[str, None] = '23dfe50b231a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('first_interview_questions', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('second_interview_questions', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('test_task', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'test_task')
    op.drop_column('candidates', 'second_interview_questions')
    op.drop_column('candidates', 'first_interview_questions')
    # ### end Alembic commands ###
