"""обавление поля test_task

Revision ID: d0f1a0c87683
Revises: 85acee4d5f51
Create Date: 2024-11-03 21:56:17.418214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f1a0c87683'
down_revision: Union[str, None] = '85acee4d5f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('test_task', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'test_task')
    # ### end Alembic commands ###
