"""Добавление поля test_task

Revision ID: e5771bcd2b86
Revises: d0f1a0c87683
Create Date: 2024-11-03 21:58:20.234845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5771bcd2b86'
down_revision: Union[str, None] = 'd0f1a0c87683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
